### ISSUE TITLE
Game win incorrectly detected

### ISSUE THREAD

**Issue by steji113** [mattmemmesheimer/minesearch-reboot#11]
The game should be won only when all cells that do not contain a mine are revealed. This is as opposed to the current behavior of the game being won when all of the mine cells are flagged.

**Comment by mattmemmesheimer** [comment]
I ran into this today while playing a game.  I remember a while back I wasn't sure what the behavior should be and never re-visited it.  Good catch.

**Comment by steji113** [comment]
According to this: http://www.minesweepers.org/object.asp flagging of mine cells should be completely optional.

**Comment by mattmemmesheimer** [comment]
Oh no!  I didn't know that.

**Comment by steji113** [comment]
Now you just need some continuous integration to catch broken unit tests on each merge!
