### ISSUE TITLE
Upper left counter does not go negative

### ISSUE THREAD

**Issue by steji113** [mattmemmesheimer/minesearch-reboot#12]
The counter in the upper left hand corner should be equal to {number of mines} - {flagged cells}. Thus if you place too many flags, the counter should go negative.

See here: http://www.minesweepers.org/details.asp

Steps to reproduce:
- Start a new game
- Flag as many cells as possible until the counter goes 0.
- Observe you cannot flag any more cells.

**Comment by steji113** [comment]
This is a decent sized commit, so probably worth reviewing thoroughly. I made the DigitalDisplayView support negative numbers which was the meat of the change. I had to do some significant refactoring to accomplish this.

**Comment by mattmemmesheimer** [comment]
Ah crap...
I went to check on this issue and saw nothing had been submitted so I started working on it.  Pushed my changes and then I saw your pull request.
